services:
  php-fpm:
    build:
      context: . # Root folder is the build context
      dockerfile: ./docker/php/Dockerfile.prod
      target: production # Use the 'production' stage in the Dockerfile
    restart: unless-stopped
    volumes:
      - laravel-storage-prod:/var/www/html/storage:rw # Mount the storage volume
    networks:
      - laravel-prod
    environment:
      - APP_KEY=${APP_KEY}
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  laravel-prod:

volumes:
  laravel-storage-prod:
