include:
  - path:
      - compose.yml
      - compose.tools.yml
      - compose.prod.override.yml
services:
  web:
    build:
      context: . # Root folder is the build context
      dockerfile: ./docker/proxy/Dockerfile.prod
      target: production
    restart: unless-stopped
    volumes:
      - laravel-storage-prod:/var/www/html/storage:ro
    networks:
      - laravel-prod
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      php-fpm:
        condition: service_healthy # Wait for php-fpm health check

  postgres:
    image: postgres:18
    restart: unless-stopped
    user: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data-prod:/var/lib/postgresql
    networks:
      - laravel-prod
    # Health check for PostgreSQL
    # -----------------------------------------------------------
    # Health checks allow Docker to determine if a service is operational.
    # The 'pg_isready' command checks if PostgreSQL is ready to accept connections.
    # This prevents dependent services from starting before the database is ready.
    # -----------------------------------------------------------
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data-prod:
  redis-data:
