name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches: [develop]

env:
  AWS_REGION: us-east-1
  APPLICATION_NAME: my-application
  ENVIRONMENT_NAME: my-application-env

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Static Credentials - IAM user:
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # OIDC - IAM Role:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}}
          aws-region: ${{ env.AWS_REGION }} # us-east-1

      - name: Deploy to AWS Elastic BeansTalk
        uses: aws-actions/aws-elasticbeanstalk-deploy@v1 # Compress repo & generate deployment package, uploads it to S3, and deploys it to AWS EB
        with:
          aws-region: ${{ env.AWS_REGION }}
          application-name: ${{ env.APPLICATION_NAME }}
          environment-name: ${{ env.ENVIRONMENT_NAME }}
          version-label: "app-${{ github.sha }}"
          solution-stack-name: "64bit Amazon Linux 2023 v4.3.0 running Python 3.11"
          option-settings: |
            [
              {
                "Namespace": "aws:autoscaling:launchconfiguration",
                "OptionName": "IamInstanceProfile",
                "Value": "aws-elasticbeanstalk-ec2-role"
              },
              {
                "Namespace": "aws:elasticbeanstalk:environment",
                "OptionName": "ServiceRole",
                "Value": "aws-elasticbeanstalk-service-role"
              }
            ]
