[www]
; Increase maximum concurrent children processes
pm.max_children = 50

; Automatically restart child after requests to prevent memory leaks
pm.max_requests = 500

; Override PHP.ini values specifically for this pool
php_admin_value[memory_limit] = 512M
php_admin_value[upload_max_filesize] = 64M
php_admin_value[post_max_size] = 64M
php_admin_value[max_execution_time] = 300

; The ping URI to call the monitoring page of FPM.
ping.path = /ping

; The URI to view the FPM status page.
pm.status_path = /status

; Sharing host with Nginx so use socket
listen = /run/php/php-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660