name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches: [develop]

env:
  AWS_REGION: us-east-1
  APPLICATION_NAME: ecommerce
  ENVIRONMENT_NAME: Ecommerce-env
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # OIDC - IAM Role:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }} # us-east-1

      - name: Deploy to AWS Elastic BeansTalk
        uses: aws-actions/aws-elasticbeanstalk-deploy@v1 # Compress repo & generate deployment package, uploads it to S3, and deploys it to AWS EB
        with:
          aws-region: ${{ env.AWS_REGION }}
          application-name: ${{ env.APPLICATION_NAME }}
          environment-name: ${{ env.ENVIRONMENT_NAME }}
          version-label: "app-${{ github.sha }}"
          deployment_package: deploy.zip
          solution-stack-name: "64bit Amazon Linux 2023 v4.13.4 running Docker"
          option-settings: |
            [
              {
                "Namespace": "aws:autoscaling:launchconfiguration",
                "OptionName": "IamInstanceProfile",
                "Value": "aws-elasticbeanstalk-ec2-role"
              },
              {
                "Namespace": "aws:elasticbeanstalk:environment",
                "OptionName": "ServiceRole",
                "Value": "aws-elasticbeanstalk-service-role"
              }   
            ]
